### ISSUE TITLE
What's the expected response format from the API?

### ISSUE THREAD

**Issue by NourdineMazali** [CristalTeam/php-api-wrapper#21]
Hi All, 

Thank you for the kickass package!

Just wondering what's the expected response format from the API, currently my API returns 
`{data:{}, status: 'success'}`
which is not quite transforming to Eloquent like Object.

Thank you.

**Comment by camillebaronnet** [comment]
Hi! Thanks you a lot @NourdineMazali !

I recommend you to override the [`findOne`](https://github.com/CristalTeam/php-api-wrapper/blob/master/src/Api.php#L107) method in your custom wrapper to send back only the child `data` or to throw an exception when the status child is wrong.
