### ISSUE TITLE
CACHE DATA FROM SERVER

### ISSUE THREAD

**Issue by ElijahGM** [CristalTeam/php-api-wrapper#23]
Hello thanks for the good plugin, is there a way to cache data from api and update them in background?

**Comment by camillebaronnet** [comment]
Hi ! `Cristal\ApiWrapper\Api` uses this `https://github.com/CristalTeam/php-api-wrapper/blob/master/src/Concerns/HasCache.php` trait to provide a very simple cache during execution. I recommande you to override these methods to implement your advenced custom strategy.
