### ISSUE TITLE
Class "CustomWrapper" not found

### ISSUE THREAD

**Issue by Redcode456123** [CristalTeam/php-api-wrapper#25]
I followed the tutorial but getting error"Class "CustomWrapper" not found !
I am using Laravel.

Thanks for help.

**Comment by camillebaronnet** [comment]
The `CustomWrapper` is an implementation for the main wrapper that represents your API. You need to create your own. Read this to learn more https://github.com/CristalTeam/php-api-wrapper/blob/master/docs/more-about-wrapper.md

**Comment by Redcode456123** [comment]
Thanks Camille,
I am trying to understand it, do you have a step by step tutorial on how to  implementing it ?

thanks.

**Comment by camillebaronnet** [comment]
Sorry we don't have a step by step tutorial more detailed than this one https://github.com/CristalTeam/php-api-wrapper/blob/master/docs/work-with-laravel.md for Laravel for the moment.
