### ISSUE TITLE
Is this Project Still Maintained?

### ISSUE THREAD

**Issue by scryba** [CristalTeam/php-api-wrapper#47]
It seems to me this project has been abandoned or is it still developed and maintained?

**Comment by TZK-** [comment]
The project is not abandoned, but it is not actively developed. We use it a lot and we mainly fix bugs when we have ones.

**Comment by jorbascrumps** [comment]
It would be nice if a disclaimer was added to the project saying it is not actively developed/ in maintenance mode. I introduced this as a dependency into my app last year and now I have to put resources towards either migrating away from it or maintaining my own fork as I find some areas lacking and PRs with improvements are seemingly ignored.
